"""add_no_same_day_booking_flag_to_users.

Revision ID: a5302d822873
Revises: b88a79da5228
Create Date: 2025-09-06 14:44:12.918799

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5302d822873"
down_revision = "b88a79da5228"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("no_same_day_booking", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "no_same_day_booking")
    # ### end Alembic commands ###
