"""rework schedul model.

Revision ID: b88a79da5228
Revises: 5cc492a1f817
Create Date: 2025-09-06 12:03:45.157015

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b88a79da5228"
down_revision = "5cc492a1f817"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column("lpu_id", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "schedules",
        sa.Column("gorzdrav_patient_id", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "schedules",
        sa.Column("gorzdrav_specialist_id", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "schedules",
        sa.Column("preferred_doctors_ids", sa.JSON(), nullable=True),
    )
    op.drop_column("schedules", "preferred_doctors")
    op.drop_column("schedules", "specialist_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column(
            "specialist_id",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schedules",
        sa.Column(
            "preferred_doctors",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("schedules", "preferred_doctors_ids")
    op.drop_column("schedules", "gorzdrav_specialist_id")
    op.drop_column("schedules", "gorzdrav_patient_id")
    op.drop_column("schedules", "lpu_id")
    # ### end Alembic commands ###
