"""add external_priority column for user.

Revision ID: 1558662a10c4
Revises: a5302d822873
Create Date: 2025-09-06 15:19:14.362856

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1558662a10c4"
down_revision = "a5302d822873"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "external_priority", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "external_priority")
    # ### end Alembic commands ###
