"""make email not nullable.

Revision ID: 2f833681dc1b
Revises: f1ec0182626c
Create Date: 2025-09-06 10:28:51.850207

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f833681dc1b"
down_revision = "f1ec0182626c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patients", "email", existing_type=sa.VARCHAR(length=100), nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patients", "email", existing_type=sa.VARCHAR(length=100), nullable=True,
    )
    # ### end Alembic commands ###
