"""rework polis fields.

Revision ID: fde73dba3d61
Revises: 1558662a10c4
Create Date: 2025-09-06 15:26:13.685416

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "fde73dba3d61"
down_revision = "1558662a10c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("patients", "polis_s", nullable=True)
    op.alter_column("patients", "polis_n", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("patients", "polis_s", nullable=False)
    op.alter_column("patients", "polis_n", nullable=True)
    # ### end Alembic commands ###
