"""add polis to patient.

Revision ID: 5cc492a1f817
Revises: 2f833681dc1b
Create Date: 2025-09-06 12:02:05.478205

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5cc492a1f817"
down_revision = "2f833681dc1b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column("polis_s", sa.String(length=20), nullable=False),
    )
    op.add_column("patients", sa.Column("polis_n", sa.String(length=20), nullable=True))
    op.drop_column("patients", "gorzdrav_id")
    op.drop_column("patients", "prefer_lpu_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column(
            "prefer_lpu_id",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "patients",
        sa.Column(
            "gorzdrav_id",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("patients", "polis_n")
    op.drop_column("patients", "polis_s")
    # ### end Alembic commands ###
